name: jobapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.1
  file_picker: ^10.3.2
  firebase_app_check: ^0.4.1+1
  firebase_auth: ^6.1.1
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.2
  google_fonts: ^6.3.1
  google_sign_in: ^7.2.0
  iconsax: ^0.0.8
  image_picker: ^1.2.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/
    - asset/icons/
